# 应用服务 WEB 访问端口
server:
  port: 58080


spring:
  # Kafka配置
  kafka:
    # 生产者配置
    producer:
      # 重试次数
      retries: 3

        # 消费者配置
    consumer:
          # 消费者组
          group-id: groupA

#Apollo 配置
app:
  id: J036X0
  #应用ID
apollo:
  cluster: default                           # 指定使用哪个集群的配置
  meta: http://10.8.56.40:9001               # DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   # 是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            # 是否开启 Apollo
    namespaces: kafka-dev                    # 设置 Namespace
    eagerLoad:
      enabled: false                         # 将Apollo加载提到初始化日志系统之前
  access-key:
    secret: 6jhfdsf789554vnbhjghjgjj         # apollo access key